labels = [
    {"label": "airplane", "min_proficiency": 1},
    {"label": "alarm clock", "min_proficiency": 1},
    {"label": "ambulance", "min_proficiency": 0},
    {"label": "angel", "min_proficiency": 3},
    {"label": "animal migration", "min_proficiency": 0},
    {"label": "ant", "min_proficiency": 1},
    {"label": "anvil", "min_proficiency": 5},
    {"label": "apple", "min_proficiency": 0},
    {"label": "arm", "min_proficiency": 5},
    {"label": "asparagus", "min_proficiency": 4},
    {"label": "axe", "min_proficiency": 4},
    {"label": "backpack", "min_proficiency": 4},
    {"label": "banana", "min_proficiency": 2},
    {"label": "bandage", "min_proficiency": 5},
    {"label": "barn", "min_proficiency": 3},
    {"label": "baseball", "min_proficiency": 0},
    {"label": "baseball bat", "min_proficiency": 0},
    {"label": "basket", "min_proficiency": 3},
    {"label": "basketball", "min_proficiency": 1},
    {"label": "bat", "min_proficiency": 3},
    {"label": "bathtub", "min_proficiency": 4},
    {"label": "beach", "min_proficiency": 1},
    {"label": "bear", "min_proficiency": 5},
    {"label": "beard", "min_proficiency": 3},
    {"label": "bed", "min_proficiency": 1},
    {"label": "bee", "min_proficiency": 5},
    {"label": "belt", "min_proficiency": 4},
    {"label": "bench", "min_proficiency": 4},
    {"label": "bicycle", "min_proficiency": 1},
    {"label": "binoculars", "min_proficiency": 3},
    {"label": "bird", "min_proficiency": 0},
    {"label": "birthday cake", "min_proficiency": 3},
    {"label": "blackberry", "min_proficiency": 5},
    {"label": "blueberry", "min_proficiency": 3},
    {"label": "book", "min_proficiency": 4},
    {"label": "boomerang", "min_proficiency": 3},
    {"label": "bottlecap", "min_proficiency": 0},
    {"label": "bowtie", "min_proficiency": 5},
    {"label": "bracelet", "min_proficiency": 0},
    {"label": "brain", "min_proficiency": 4},
    {"label": "bread", "min_proficiency": 1},
    {"label": "bridge", "min_proficiency": 5},
    {"label": "broccoli", "min_proficiency": 1},
    {"label": "broom", "min_proficiency": 4},
    {"label": "bucket", "min_proficiency": 4},
    {"label": "bulldozer", "min_proficiency": 0},
    {"label": "bus", "min_proficiency": 4},
    {"label": "bush", "min_proficiency": 4},
    {"label": "butterfly", "min_proficiency": 2},
    {"label": "cactus", "min_proficiency": 2},
    {"label": "cake", "min_proficiency": 0},
    {"label": "calculator", "min_proficiency": 3},
    {"label": "calendar", "min_proficiency": 4},
    {"label": "camel", "min_proficiency": 0},
    {"label": "camera", "min_proficiency": 2},
    {"label": "camouflage", "min_proficiency": 5},
    {"label": "campfire", "min_proficiency": 5},
    {"label": "candle", "min_proficiency": 3},
    {"label": "cannon", "min_proficiency": 3},
    {"label": "canoe", "min_proficiency": 0},
    {"label": "car", "min_proficiency": 0},
    {"label": "carrot", "min_proficiency": 3},
    {"label": "castle", "min_proficiency": 3},
    {"label": "cat", "min_proficiency": 5},
    {"label": "ceiling fan", "min_proficiency": 3},
    {"label": "cell phone", "min_proficiency": 3},
    {"label": "cello", "min_proficiency": 3},
    {"label": "chair", "min_proficiency": 2},
    {"label": "chandelier", "min_proficiency": 5},
    {"label": "church", "min_proficiency": 3},
    {"label": "circle", "min_proficiency": 5},
    {"label": "clarinet", "min_proficiency": 0},
    {"label": "clock", "min_proficiency": 3},
    {"label": "cloud", "min_proficiency": 0},
    {"label": "coffee cup", "min_proficiency": 5},
    {"label": "compass", "min_proficiency": 3},
    {"label": "computer", "min_proficiency": 4},
    {"label": "cookie", "min_proficiency": 3},
    {"label": "cooler", "min_proficiency": 4},
    {"label": "couch", "min_proficiency": 2},
    {"label": "cow", "min_proficiency": 5},
    {"label": "crab", "min_proficiency": 1},
    {"label": "crayon", "min_proficiency": 4},
    {"label": "crocodile", "min_proficiency": 2},
    {"label": "crown", "min_proficiency": 2},
    {"label": "cruise ship", "min_proficiency": 2},
    {"label": "cup", "min_proficiency": 1},
    {"label": "diamond", "min_proficiency": 5},
    {"label": "dishwasher", "min_proficiency": 0},
    {"label": "diving board", "min_proficiency": 2},
    {"label": "dog", "min_proficiency": 2},
    {"label": "dolphin", "min_proficiency": 1},
    {"label": "donut", "min_proficiency": 1},
    {"label": "door", "min_proficiency": 0},
    {"label": "dragon", "min_proficiency": 3},
    {"label": "dresser", "min_proficiency": 2},
    {"label": "drill", "min_proficiency": 2},
    {"label": "drums", "min_proficiency": 0},
    {"label": "duck", "min_proficiency": 4},
    {"label": "dumbbell", "min_proficiency": 1},
    {"label": "ear", "min_proficiency": 5},
    {"label": "elbow", "min_proficiency": 1},
    {"label": "elephant", "min_proficiency": 4},
    {"label": "envelope", "min_proficiency": 1},
    {"label": "eraser", "min_proficiency": 5},
    {"label": "eye", "min_proficiency": 5},
    {"label": "eyeglasses", "min_proficiency": 5},
    {"label": "face", "min_proficiency": 5},
    {"label": "fan", "min_proficiency": 2},
    {"label": "feather", "min_proficiency": 0},
    {"label": "fence", "min_proficiency": 2},
    {"label": "finger", "min_proficiency": 2},
    {"label": "fire hydrant", "min_proficiency": 5},
    {"label": "fireplace", "min_proficiency": 3},
    {"label": "firetruck", "min_proficiency": 3},
    {"label": "fish", "min_proficiency": 1},
    {"label": "flamingo", "min_proficiency": 5},
    {"label": "flashlight", "min_proficiency": 5},
    {"label": "flip flops", "min_proficiency": 0},
    {"label": "floor lamp", "min_proficiency": 1},
    {"label": "flower", "min_proficiency": 1},
    {"label": "flying saucer", "min_proficiency": 1},
    {"label": "foot", "min_proficiency": 5},
    {"label": "fork", "min_proficiency": 3},
    {"label": "frog", "min_proficiency": 2},
    {"label": "frying pan", "min_proficiency": 5},
    {"label": "garden", "min_proficiency": 0},
    {"label": "garden hose", "min_proficiency": 3},
    {"label": "giraffe", "min_proficiency": 3},
    {"label": "goatee", "min_proficiency": 2},
    {"label": "golf club", "min_proficiency": 5},
    {"label": "grapes", "min_proficiency": 0},
    {"label": "grass", "min_proficiency": 0},
    {"label": "guitar", "min_proficiency": 3},
    {"label": "hamburger", "min_proficiency": 0},
    {"label": "hammer", "min_proficiency": 0},
    {"label": "hand", "min_proficiency": 1},
    {"label": "harp", "min_proficiency": 3},
    {"label": "hat", "min_proficiency": 0},
    {"label": "headphones", "min_proficiency": 1},
    {"label": "hedgehog", "min_proficiency": 0},
    {"label": "helicopter", "min_proficiency": 2},
    {"label": "helmet", "min_proficiency": 1},
    {"label": "hexagon", "min_proficiency": 3},
    {"label": "hockey puck", "min_proficiency": 4},
    {"label": "hockey stick", "min_proficiency": 3},
    {"label": "horse", "min_proficiency": 4},
    {"label": "hospital", "min_proficiency": 1},
    {"label": "hot air balloon", "min_proficiency": 5},
    {"label": "hot dog", "min_proficiency": 0},
    {"label": "hot tub", "min_proficiency": 4},
    {"label": "hourglass", "min_proficiency": 2},
    {"label": "house", "min_proficiency": 5},
    {"label": "house plant", "min_proficiency": 1},
    {"label": "hurricane", "min_proficiency": 3},
    {"label": "ice cream", "min_proficiency": 2},
    {"label": "jacket", "min_proficiency": 4},
    {"label": "jail", "min_proficiency": 5},
    {"label": "kangaroo", "min_proficiency": 5},
    {"label": "key", "min_proficiency": 5},
    {"label": "keyboard", "min_proficiency": 2},
    {"label": "knee", "min_proficiency": 0},
    {"label": "ladder", "min_proficiency": 3},
    {"label": "lantern", "min_proficiency": 5},
    {"label": "laptop", "min_proficiency": 4},
    {"label": "leaf", "min_proficiency": 5},
    {"label": "leg", "min_proficiency": 1},
    {"label": "light bulb", "min_proficiency": 1},
    {"label": "lighthouse", "min_proficiency": 2},
    {"label": "lightning", "min_proficiency": 1},
    {"label": "line", "min_proficiency": 0},
    {"label": "lion", "min_proficiency": 0},
    {"label": "lipstick", "min_proficiency": 5},
    {"label": "lobster", "min_proficiency": 4},
    {"label": "lollipop", "min_proficiency": 0},
    {"label": "mailbox", "min_proficiency": 1},
    {"label": "map", "min_proficiency": 0},
    {"label": "marker", "min_proficiency": 3},
    {"label": "matches", "min_proficiency": 2},
    {"label": "megaphone", "min_proficiency": 5},
    {"label": "mermaid", "min_proficiency": 2},
    {"label": "microphone", "min_proficiency": 3},
    {"label": "microwave", "min_proficiency": 0},
    {"label": "monkey", "min_proficiency": 2},
    {"label": "moon", "min_proficiency": 5},
    {"label": "mosquito", "min_proficiency": 0},
    {"label": "motorbike", "min_proficiency": 4},
    {"label": "mountain", "min_proficiency": 2},
    {"label": "mouse", "min_proficiency": 1},
    {"label": "moustache", "min_proficiency": 2},
    {"label": "mouth", "min_proficiency": 4},
    {"label": "mug", "min_proficiency": 4},
    {"label": "mushroom", "min_proficiency": 5},
    {"label": "nail", "min_proficiency": 5},
    {"label": "necklace", "min_proficiency": 3},
    {"label": "nose", "min_proficiency": 2},
    {"label": "ocean", "min_proficiency": 2},
    {"label": "octagon", "min_proficiency": 5},
    {"label": "octopus", "min_proficiency": 2},
    {"label": "onion", "min_proficiency": 3},
    {"label": "oven", "min_proficiency": 0},
    {"label": "owl", "min_proficiency": 2},
    {"label": "paint can", "min_proficiency": 5},
    {"label": "paintbrush", "min_proficiency": 4},
    {"label": "palm tree", "min_proficiency": 2},
    {"label": "panda", "min_proficiency": 0},
    {"label": "pants", "min_proficiency": 2},
    {"label": "paper clip", "min_proficiency": 1},
    {"label": "parachute", "min_proficiency": 3},
    {"label": "parrot", "min_proficiency": 5},
    {"label": "passport", "min_proficiency": 2},
    {"label": "peanut", "min_proficiency": 5},
    {"label": "pear", "min_proficiency": 0},
    {"label": "peas", "min_proficiency": 3},
    {"label": "pencil", "min_proficiency": 2},
    {"label": "penguin", "min_proficiency": 3},
    {"label": "piano", "min_proficiency": 4},
    {"label": "pickup truck", "min_proficiency": 0},
    {"label": "picture frame", "min_proficiency": 3},
    {"label": "pig", "min_proficiency": 3},
    {"label": "pillow", "min_proficiency": 1},
    {"label": "pineapple", "min_proficiency": 3},
    {"label": "pizza", "min_proficiency": 2},
    {"label": "pliers", "min_proficiency": 2},
    {"label": "police car", "min_proficiency": 0},
    {"label": "pond", "min_proficiency": 0},
    {"label": "pool", "min_proficiency": 0},
    {"label": "popsicle", "min_proficiency": 4},
    {"label": "postcard", "min_proficiency": 5},
    {"label": "potato", "min_proficiency": 4},
    {"label": "power outlet", "min_proficiency": 4},
    {"label": "purse", "min_proficiency": 2},
    {"label": "rabbit", "min_proficiency": 0},
    {"label": "raccoon", "min_proficiency": 3},
    {"label": "radio", "min_proficiency": 5},
    {"label": "rain", "min_proficiency": 0},
    {"label": "rainbow", "min_proficiency": 4},
    {"label": "rake", "min_proficiency": 2},
    {"label": "remote control", "min_proficiency": 3},
    {"label": "rhinoceros", "min_proficiency": 4},
    {"label": "river", "min_proficiency": 1},
    {"label": "roller coaster", "min_proficiency": 2},
    {"label": "rollerskates", "min_proficiency": 1},
    {"label": "sailboat", "min_proficiency": 2},
    {"label": "sandwich", "min_proficiency": 2},
    {"label": "saw", "min_proficiency": 5},
    {"label": "saxophone", "min_proficiency": 3},
    {"label": "school bus", "min_proficiency": 5},
    {"label": "scissors", "min_proficiency": 0},
    {"label": "scorpion", "min_proficiency": 0},
    {"label": "screwdriver", "min_proficiency": 3},
    {"label": "sea turtle", "min_proficiency": 4},
    {"label": "see saw", "min_proficiency": 2},
    {"label": "shark", "min_proficiency": 4},
    {"label": "sheep", "min_proficiency": 5},
    {"label": "shoe", "min_proficiency": 2},
    {"label": "shorts", "min_proficiency": 1},
    {"label": "shovel", "min_proficiency": 5},
    {"label": "sink", "min_proficiency": 2},
    {"label": "skateboard", "min_proficiency": 5},
    {"label": "skull", "min_proficiency": 1},
    {"label": "skyscraper", "min_proficiency": 1},
    {"label": "sleeping bag", "min_proficiency": 1},
    {"label": "smiley face", "min_proficiency": 4},
    {"label": "snail", "min_proficiency": 1},
    {"label": "snake", "min_proficiency": 1},
    {"label": "snorkel", "min_proficiency": 3},
    {"label": "snowflake", "min_proficiency": 4},
    {"label": "snowman", "min_proficiency": 1},
    {"label": "soccer ball", "min_proficiency": 4},
    {"label": "sock", "min_proficiency": 4},
    {"label": "speedboat", "min_proficiency": 5},
    {"label": "spider", "min_proficiency": 2},
    {"label": "spoon", "min_proficiency": 5},
    {"label": "spreadsheet", "min_proficiency": 0},
    {"label": "square", "min_proficiency": 5},
    {"label": "squiggle", "min_proficiency": 0},
    {"label": "squirrel", "min_proficiency": 3},
    {"label": "stairs", "min_proficiency": 4},
    {"label": "star", "min_proficiency": 5},
    {"label": "steak", "min_proficiency": 3},
    {"label": "stereo", "min_proficiency": 4},
    {"label": "stethoscope", "min_proficiency": 3},
    {"label": "stitches", "min_proficiency": 4},
    {"label": "stop sign", "min_proficiency": 5},
    {"label": "stove", "min_proficiency": 2},
    {"label": "strawberry", "min_proficiency": 3},
    {"label": "streetlight", "min_proficiency": 3},
    {"label": "string bean", "min_proficiency": 4},
    {"label": "submarine", "min_proficiency": 1},
    {"label": "suitcase", "min_proficiency": 2},
    {"label": "sun", "min_proficiency": 1},
    {"label": "swan", "min_proficiency": 2},
    {"label": "sweater", "min_proficiency": 3},
    {"label": "swing set", "min_proficiency": 3},
    {"label": "sword", "min_proficiency": 5},
    {"label": "t-shirt", "min_proficiency": 5},
    {"label": "table", "min_proficiency": 4},
    {"label": "teapot", "min_proficiency": 2},
    {"label": "teddy-bear", "min_proficiency": 0},
    {"label": "telephone", "min_proficiency": 0},
    {"label": "television", "min_proficiency": 4},
    {"label": "tennis racquet", "min_proficiency": 5},
    {"label": "tent", "min_proficiency": 4},
    {"label": "The Eiffel Tower", "min_proficiency": 3},
    {"label": "The Great Wall of China", "min_proficiency": 0},
    {"label": "The Mona Lisa", "min_proficiency": 4},
    {"label": "tiger", "min_proficiency": 4},
    {"label": "toaster", "min_proficiency": 0},
    {"label": "toe", "min_proficiency": 4},
    {"label": "toilet", "min_proficiency": 3},
    {"label": "tooth", "min_proficiency": 4},
    {"label": "toothbrush", "min_proficiency": 5},
    {"label": "toothpaste", "min_proficiency": 4},
    {"label": "tornado", "min_proficiency": 1},
    {"label": "tractor", "min_proficiency": 0},
    {"label": "traffic light", "min_proficiency": 2},
    {"label": "train", "min_proficiency": 1},
    {"label": "tree", "min_proficiency": 3},
    {"label": "triangle", "min_proficiency": 4},
    {"label": "trombone", "min_proficiency": 4},
    {"label": "truck", "min_proficiency": 5},
    {"label": "trumpet", "min_proficiency": 1},
    {"label": "umbrella", "min_proficiency": 5},
    {"label": "underwear", "min_proficiency": 0},
    {"label": "van", "min_proficiency": 0},
    {"label": "vase", "min_proficiency": 2},
    {"label": "violin", "min_proficiency": 5},
    {"label": "washing machine", "min_proficiency": 2},
    {"label": "watermelon", "min_proficiency": 4},
    {"label": "waterslide", "min_proficiency": 4},
    {"label": "whale", "min_proficiency": 0},
    {"label": "wheel", "min_proficiency": 1},
    {"label": "windmill", "min_proficiency": 5},
    {"label": "wine bottle", "min_proficiency": 2},
    {"label": "wine glass", "min_proficiency": 2},
    {"label": "wristwatch", "min_proficiency": 1},
    {"label": "yoga", "min_proficiency": 1},
    {"label": "zebra", "min_proficiency": 5},
    {"label": "zigzag", "min_proficiency": 0},
]
