labels = [
    "car (sedan)",
    "crane (machine)",
    "bear (animal)",
    "motorbike",
    "parking meter",
    "bathtub",
    "eyeglasses",
    "flying saucer",
    "crocodile",
    "helicopter",
    "pumpkin",
    "rollerblades",
    "trombone",
    "cake",
    "donut",
    "ipod",
    "pizza",
    "saxophone",
    "parrot",
    "cannon",
    "cactus",
    "pickup truck",
    "armchair",
    "bee",
    "streetlight",
    "fork",
    "backpack",
    "person walking",
    "pretzel",
    "scissors",
    "mermaid",
    "dolphin",
    "shovel",
    "fish",
    "castle",
    "ship",
    "pig",
    "binoculars",
    "barn",
    "diamond",
    "palm tree",
    "eye",
    "pear",
    "toilet",
    "house",
    "windmill",
    "fire hydrant",
    "potted plant",
    "truck",
    "skyscraper",
    "bread",
    "panda",
    "flashlight",
    "snail",
    "sea turtle",
    "umbrella",
    "screwdriver",
    "sheep",
    "bed",
    "shark",
    "octopus",
    "dog",
    "tractor",
    "bell",
    "toothbrush",
    "head",
    "cigarette",
    "cat",
    "satellite",
    "wine-bottle",
    "mouse (animal)",
    "snowman",
    "angel",
    "microscope",
    "bowl",
    "bulldozer",
    "kangaroo",
    "tomato",
    "scorpion",
    "penguin",
    "head-phones",
    "bicycle",
    "book",
    "cow",
    "axe",
    "snake",
    "calculator",
    "t-shirt",
    "suitcase",
    "floor lamp",
    "comb",
    "skateboard",
    "pineapple",
    "violin",
    "cell phone",
    "zebra",
    "monkey",
    "candle",
    "loudspeaker",
    "keyboard",
    "frying-pan",
    "teapot",
    "door handle",
    "boomerang",
    "teddy-bear",
    "walkie talkie",
    "train",
    "bench",
    "squirrel",
    "snowboard",
    "nose",
    "butterfly",
    "sword",
    "race car",
    "mug",
    "wrist-watch",
    "pen",
    "wineglass",
    "cup",
    "camera",
    "cloud",
    "dragon",
    "mailbox",
    "banana",
    "ant",
    "purse",
    "bridge",
    "carrot",
    "elephant",
    "rainbow",
    "crown",
    "vase",
    "speed-boat",
    "guitar",
    "mosquito",
    "door",
    "giraffe",
    "moon",
    "shoe",
    "hamburger",
    "teacup",
    "laptop",
    "socks",
    "basket",
    "submarine",
    "bush",
    "alarm clock",
    "rabbit",
    "helmet",
    "santa claus",
    "rifle",
    "rooster",
    "traffic light",
    "blimp",
    "sponge bob",
    "trumpet",
    "lightbulb",
    "sailboat",
    "tent",
    "flower with stem",
    "bus",
    "wheelbarrow",
    "syringe",
    "harp",
    "hedgehog",
    "trousers",
    "baseball bat",
    "person sitting",
    "megaphone",
    "power outlet",
    "fan",
    "hand",
    "arm",
    "paper clip",
    "standing bird",
    "grapes",
    "beer-mug",
    "airplane",
    "apple",
    "computer monitor",
    "strawberry",
    "skull",
    "hat",
    "key",
    "ice-cream-cone",
    "ear",
    "canoe",
    "parachute",
    "chandelier",
    "hourglass",
    "sun",
    "computer-mouse",
    "tv",
    "lion",
    "space shuttle",
    "brain",
    "human-skeleton",
    "tablelamp",
    "hammer",
    "envelope",
    "ladder",
    "telephone",
    "duck",
    "swan",
    "couch",
    "mushroom",
    "frog",
    "leaf",
    "tire",
    "table",
    "grenade",
    "bottle opener",
    "tooth",
    "seagull",
    "spoon",
    "crab",
    "suv",
    "pipe (for smoking)",
    "microphone",
    "present",
    "knife",
    "foot",
    "ashtray",
    "horse",
    "face",
    "mouth",
    "stapler",
    "piano",
    "pigeon",
    "tree",
    "cabinet",
    "van",
    "hot-dog",
    "radio",
    "camel",
    "lobster",
    "feather",
    "owl",
    "tiger",
    "bookshelf",
    "flying bird",
    "satellite dish",
    "spider",
    "revolver",
    "church",
    "hot air balloon",
    "tennis-racket",
    "wheel",
    "chair",
    "lighter",
]
